# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180530_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_req',
            field=models.CharField(default='', max_length=300, verbose_name='\u8bfe\u7a0b\u987b\u77e5'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_tips',
            field=models.CharField(default='', max_length=300, verbose_name='\u8001\u5e08\u63d0\u793a'),
        ),
    ]
