# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-25 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(1, '\u7537'), (2, '\u5973')], default='female', max_length=6),
        ),
    ]
