# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-26 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orginazition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='desc',
            field=models.CharField(default='', max_length=200, verbose_name='\u57ce\u5e02\u63cf\u8ff0'),
        ),
    ]
