# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-27 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orginazition', '0002_auto_20180526_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '\u8bfe\u7a0b\u673a\u6784', 'verbose_name_plural': '\u8bfe\u7a0b\u673a\u6784'},
        ),
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '\u57f9\u8bad\u673a\u6784'), ('gr', '\u4e2a\u4eba'), ('gx', '\u9ad8\u6821')], default='pxjg', max_length=20, verbose_name='\u57f9\u8bad\u673a\u6784'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='org/%Y/%m', verbose_name='\u673a\u6784LOGO'),
        ),
    ]
