# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-28 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orginazition', '0004_auto_20180528_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='\u8001\u5e08\u5934\u50cf'),
        ),
    ]
